### ISSUE TITLE
Popups on global map

### ISSUE THREAD

**Issue by BegTheCat** [ControlTheBit/geocachingUtils#109]
Not shown cache popup on global map when clicking on cache icon.

![screenshot-www_geocaching_com-2024_10_06-05_23_54](https://github.com/user-attachments/assets/c48b79bd-b820-4627-b0e1-584cd7e91fdd)

When I turn off the extension, everything works.

**Comment by leobut** [comment]
Thank you for the report, I will look into it later in November / beginning of December as I am currently vacation.

**Comment by leobut** [comment]
The fix is currently dragging itself as I am very busy with life, but will hopefully be able to look into this in January/February. If you require a quick fix and want to provide a PR, I am more than happy to have a look and appreciate the help 😄

**Comment by leobut** [comment]
Ok, this didn't let me go. I had to take a quick look into this right now. And it's fixed with the new version that will go out later today :)

**Comment by leobut** [comment]
Fixed with https://github.com/leobut/geocachingUtils/commit/9da99c29b89409f50cfad2e8ccb63122ce3eb60e
