### ISSUE TITLE
Friends list always empty

### ISSUE THREAD

**Issue by Ironhawk67** [ControlTheBit/geocachingUtils#83]
The Friends list has stop working. It always reports "No friend logs" even if several friends have logged the cache.

**Comment by leobut** [comment]
@Ironhawk67 Hello and sorry that you get a reply too late. I must have missed the email from Github.

I have been looking into this and am struggling to reproduce it. It still works for me without any issues.

Can you maybe give me more information? Like for example which geocache it is, what chrome extensions you are using, and maybe even a screenshot?

Anything helps 😃 

Thank you

**Comment by Ironhawk67** [comment]
Hi!

I had forgtten that I reported this. :-)
It must have been some temporary bug back then. Maybe with a specific version of the geocaching.com website or a Chrome update.
The Friends Logs is working just fine now, so ignore this bug report.

**Comment by leobut** [comment]
Awesome 😄  Thanks for reporting though!
